language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: b1a52efa-a488-4e76-9b0b-332049530a9c
  app: jili-addressbook
  on:
    repo: dindanmao/addressbook
    branch: todo_tasks
